### ISSUE TITLE
Building Nextcloud-Signal Docker Containers... [FAIL]

### ISSUE THREAD

**Issue by ralfrupf1976** [deeztek/deeztek-docker#4]
I just installed Docker on a fresh Ubuntu 22.04 Server and started the Installation. Everything seems to work fine but at the end it says:

Building Nextcloud-Signal Docker Containers... [FAIL]

a simple docker ps shows that no containers are running.

**Comment by deeztek** [comment]
Haven't successfully tested in 22.04 yet. There should be a log file (install_log-$TIMESTAMP.log) from where you started the script. Please post the contents of the log file here to see what hapenned.

Thanks

**Comment by ralfrupf1976** [comment]
Tested also with Ubuntu 20.04 - same result. Building oft the Containers failed
[Logfile.txt](https://github.com/deeztek/deeztek-docker/files/10553823/Logfile.txt)

**Comment by deeztek** [comment]
Just tested on Ubuntu 20.04 LTS and it built and launched the containers without any problems. Is docker AND docker-compose installed on your machine? I'm using docker-compose v2.15.1 (latest version) if that helps you. I have attached the log file from the successful installation to see if you can pinpoint a problem. 

Thanks

[install_log-02-01-2023-2358.log](https://github.com/deeztek/deeztek-docker/files/10563243/install_log-02-01-2023-2358.log)

**Comment by RepLicanT-UHD** [comment]
I can confirm that everything has built and works perfectly in a real-world working environment on Ubuntu 20.04. I'd like to take this opportunity to thank the author for his contributions. According to the logs, both the STUN/TURN servers and the HPB server are actively involved in Nextcloud AIO work, particularly during voice communication and video conferencing. This is evident in both the traffic to them and the noticeable increase in CPU load on the HPB server during video calls. Thank you once more for your efforts.

**Comment by deeztek** [comment]
> Just tested on Ubuntu 20.04 LTS and it built and launched the containers without any problems. Is docker AND docker-compose installed on your machine? I'm using docker-compose v2.15.1 (latest version) if that helps you. I have attached the log file from the successful installation to see if you can pinpoint a problem.
> 
> Thanks
> 
> [install_log-02-01-2023-2358.log](https://github.com/deeztek/deeztek-docker/files/10563243/install_log-02-01-2023-2358.log)

I also want to make sure that you don't skip through any of the script prompts assuming that simply pressing enter it enters a default value. You cannot leave any of the script prompts blank.

**Comment by deeztek** [comment]
I'm going to test on Ubuntu 22.04

> I can confirm that everything has built and works perfectly in a real-world working environment on Ubuntu 20.04. I'd like to take this opportunity to thank the author for his contributions. According to the logs, both the STUN/TURN servers and the HPB server are actively involved in Nextcloud AIO work, particularly during voice communication and video conferencing. This is evident in both the traffic to them and the noticeable increase in CPU load on the HPB server during video calls. Thank you once more for your efforts.

Thanks. Your feedback is much appreciated!

**Comment by ralfrupf1976** [comment]
After your feedbacks I think the problem is Proxmox. I know that there are some problems using docker or docker-compose with proxmox. I try to figure out why a LXC oder VM with Ubuntu 20.04 or 22.04 make problems.
