### ISSUE TITLE
Running Nextcloud Signaling Server Behind Reverse Proxy

### ISSUE THREAD

**Issue by Kendrick0349** [deeztek/deeztek-docker#5]
Is it possible to run the Nextcloud standalone signaling server behind a reverse proxy using the script? I would like to free up ports 80 and 443 in order to run Nginx Proxy Manager, and let Nginx Proxy Manager handle SSL certificates.

Many thanks for your help!

**Comment by deeztek** [comment]
Run the script, it will cinfigure everything and it will try to start the containers but it will fail. Then modify the docker-compose.yml file and try changing the  nextcloud_spreed_nginx container ports to a different host ports and point your reverse proxy to those ports and restarr the stack. Example:

```
networks:
      - spreed
    ports:
      - 8080:80
      - 8443:443
```

`docker-compose up -d`

**Comment by digitalrevisor** [comment]
Hi, did @Kendrick0349 ever get this to work?
I'm not quite sure how to write the Nginx config for this. 
I have tried something like this:

`server {
    listen 443;

    server_name example.com;

    location / {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;

        proxy_pass http://localhost:8443/;
    }
}`

**Comment by deeztek** [comment]
@digitalrevisor is the Nginx server outside the spreed docker stack? i.e. is it a separate nginx server that is not related to the spreed containers?

**Comment by digitalrevisor** [comment]
@deeztek yes.

**Comment by deeztek** [comment]
If it's a different machine, then the following line should point to the IP of your docker server:

proxy_pass http://localhost:8443/;

**Comment by digitalrevisor** [comment]
@deeztek  sorry for the late response, we tried for a bit more then we had to abandon the idea for now. 
But we will try again soon, then ill try what you mentioned above.
And thank you for your quick replies.
