### ISSUE TITLE
Nextcloud hpb support for Nextcloud v26.x.x

### ISSUE THREAD

**Issue by digitalrevisor** [deeztek/deeztek-docker#6]
Are there any plans to add support for Nextcloud V26?

I have not noticed any old features stop working but the new features do not work.
The HPB works on V26 but users always get an error message telling users to contact administrators to update HPB

I do not have a solution or any idea of how to update it myself.
I do not expect you to prioritize it but just wondering if it's on the table.

**Comment by deeztek** [comment]
Hi,

Have you tried the upgrade script?

https://github.com/deeztek/deeztek-docker/blob/master/Linux/nextcloud-spreed-signaling/upgrade_spreed.sh

**Comment by digitalrevisor** [comment]
Yes I have tried it, but now that I am looking at the script I see it pulls from strukturag/nextcloud-spreed-signaling
and that repo is not updated yet I guess.
But the script runs and completes.

Also, I get this when running the script:

- ./upgrade_spreed.sh: line 5: start_spinner: command not found

could that be messing with things?

Edit:
Spinner is installed
- spinner is already the newest version (1.2.4-5)

Edit:
adding " source "$(pwd)/spinner.sh" " to upgrade_spreed.sh fixed the command not found issue.

Edit: 
There seems to be a larger issue with the updated strukturag/nextcloud-spreed-signaling repo that makes building with 'docker-compose build' fail.

failed to parse platform : "" is an invalid component of "": platform specifier component must match "^[A-Za-z0-9_-]+$": invalid argument

That's why the upgrade script does not work. it cant build after updating
Also, there are issues with the update script. 

cd /opt/nextcloud-spreed-signaling && git remote add origin https://github.com/strukturag/nextcloud-spreed-signaling.git && git pull origin master

This command does not work because the repo already exists and is already on the master branch. 
Not sure if this is meant to only run once after updates though.
Changing to 'cd /opt/nextcloud-spreed-signaling && git pull' made the script work, but still an issue with the strukturag repo.

I have tried to remove all files related to this repo and the strukturtag repo and install it all fresh. that did also not work.

**Comment by deeztek** [comment]
Not surprising. They have changed the repo structure more than once. Let me take a look and get back to you.

**Comment by digitalrevisor** [comment]
I have been testing some stuff now and was able to build the containers with docker compose v2.18.1 and not docker-compose v1.29.2

Edit: 
I ran install script then cd to /opt/nextcloud-spreed-signaling then ran docker compose build, then docker compose up.
Now it works great.

**Comment by deeztek** [comment]
On Ubuntu 22.04 both docker compose and docker-compose work:

#docker-compose -v
Docker Compose version v2.16.0

#docker compose version
Docker Compose version v2.16.0

If you upgraded your docker compose, you should have created a shell alias to redirect docker-compose to docker compose which would not cause issues with scripts from 1.x. I suppose I should upgrade the commands in the scripts also.

Either way, I'm glad it's now working.

**Comment by digitalrevisor** [comment]
Aha!, our server is on Ubuntu 20.04 LTS. But I'll explore that later, thanks for quick and helpful replies 😀

**Comment by deeztek** [comment]
np. Please see the following article if you wish to create a bash alias for docker-compose:

[https://www.howtogeek.com/devops/how-to-upgrade-to-docker-compose-v2/](https://www.howtogeek.com/devops/how-to-upgrade-to-docker-compose-v2/)
